version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./proyComBaby:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/zz-custom-php.ini:ro
      - ./docker/logs:/var/log
      #- "C:/Users/jonat/Documents/Repositorio/proyBabylovec:/var/www/html"
    depends_on:
      - db

  db:
    image: percona/percona-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: babylovec
      MYSQL_USER: jonathan
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
